lsst/utils

- README.rst
- doc/.gitignore
- doc/conf.py
- doc/index.rst
- doc/lsst.utils/index.rst
- doc/manifest.yaml
- doc/utils/index.rst
- python/lsst/utils/tests.py
- python/lsst/utils/wrappers.py
Add sphinx support to `doc/` and cleanup numpydoc so some docs build.
> Add sphinx support

- python/lsst/utils/tests.py
Now test for start and end of passwd file path.
> Adjust test for NERSC password file

- python/lsst/utils/deprecated.py
With thanks / apologies to K-T Lim.
> Augment docstring.

- setup.cfg
Otherwise pip install won't realize it is needed.
> DM-20970 (hotfix): Add astropy dependency to setup.cfg

- .github/workflows/docstyle.yaml
- .github/workflows/formatting.yaml
- .github/workflows/lint.yaml
- .github/workflows/mypy.yaml
- types.txt
> switch to reusable workflows

- .github/workflows/build.yaml
- doc/changes/DM-31721.feature.rst
- doc/lsst.utils/CHANGES.rst
> DM-32843: Add v23 release notes

- .github/workflows/build.yaml
- README.rst
- doc/changes/DM-20970.api.rst
- doc/changes/DM-29370.feature.rst
- doc/changes/DM-29701.api.rst
- doc/changes/DM-31141.feature.rst
- doc/changes/DM-31721.feature.rst
- doc/changes/DM-31722.feature.rst
- doc/changes/DM-32142.feature.rst
- doc/changes/DM-32408.feature.rst
- doc/changes/DM-32661.perf.rst
- doc/changes/DM-33331.feature.rst
- doc/changes/DM-33403.feature.rst
- doc/changes/DM-33622.feature.rst
- doc/changes/DM-33919.feature.rst
- doc/changes/DM-33934.api.rst
- doc/changes/DM-34208.feature.rst
- doc/lsst.utils/CHANGES.rst
- pyproject.toml
> DM-36034: v24.0.0 release notes

- README.rst
- doc/changes/DM-20970.api.rst
- doc/changes/DM-29370.feature.rst
- doc/changes/DM-29701.api.rst
- doc/changes/DM-31141.feature.rst
- doc/changes/DM-31721.feature.rst
- doc/changes/DM-31722.feature.rst
- doc/changes/DM-32142.feature.rst
- doc/changes/DM-32408.feature.rst
- doc/changes/DM-32661.perf.rst
- doc/changes/DM-33331.feature.rst
- doc/changes/DM-33403.feature.rst
- doc/changes/DM-33622.feature.rst
- doc/changes/DM-33919.feature.rst
- doc/changes/DM-33934.api.rst
- doc/changes/DM-34208.feature.rst
- doc/lsst.utils/CHANGES.rst
- pyproject.toml
> DM-36034: Port to v24.0.0 release notes to main

- README.rst
> DM-36034 (hotfix): Fix branch for code coverage

- README.rst
> Fix link to code coverage information in readme

- .pre-commit-config.yaml
- python/lsst/utils/classes.py
- python/lsst/utils/logging.py
- python/lsst/utils/packages.py
- ups/utils.table
> DM-36927: Remove MYPYPATH setting

- doc/changes/DM-36960.misc.rst
- tests/test_usage.py
> DM-36960: utils testGetCurrentMemUsage failure

- .pre-commit-config.yaml
- doc/changes/DM-35697.feature.rst
- doc/changes/DM-36108.misc.md
- doc/changes/DM-36960.misc.rst
- doc/lsst.utils/CHANGES.rst
- pyproject.toml
- python/lsst/utils/ellipsis.py
- tests/test_wrappers.py
> DM-38065: V25 release notes (v25.0.x)

- doc/changes/DM-35697.feature.rst
- doc/changes/DM-36108.misc.md
- doc/changes/DM-36960.misc.rst
- doc/lsst.utils/CHANGES.rst
- pyproject.toml
> DM-38065: Copy v25 release notes to main

- .github/workflows/build_docs.yaml
- doc/conf.py
- doc/lsst.utils/CHANGES.rst
- python/lsst/utils/iteration.py
- python/lsst/utils/logging.py
- python/lsst/utils/packages.py
- python/lsst/utils/timer.py
> DM-39803: Cleanup docs for Sphinx nitpick mode

- .github/workflows/build.yaml
- pyproject.toml
> DM-39857: Stop using pytest-flake8 for testing

- doc/changes/DM-35901.feature.rst
- doc/changes/DM-35901.removal.rst
- doc/changes/DM-37534.removal.md
- doc/changes/DM-37987.feature.md
- doc/changes/DM-38386.feature.md
- doc/changes/DM-38587.bugfix.rst
- doc/changes/DM-38665.bugfix.md
- doc/changes/DM-38764.feature.md
- doc/changes/DM-38812.misc.rst
- doc/changes/DM-38900.feature.md
- doc/changes/DM-39402.misc.rst
- doc/changes/DM-39410.removal.md
- doc/changes/DM-39628.feature.rst
- doc/changes/DM-40032.feature.rst
- doc/changes/DM-40032.removal.rst
- doc/changes/DM-40367.feature.rst
- doc/changes/DM-40462.feature.md
- doc/lsst.utils/CHANGES.rst
> DM-40883: Write v26 release notes

- .github/workflows/build_docs.yaml
- doc/changes/DM-35901.feature.rst
- doc/changes/DM-35901.removal.rst
- doc/changes/DM-37534.removal.md
- doc/changes/DM-37987.feature.md
- doc/changes/DM-38386.feature.md
- doc/changes/DM-38587.bugfix.rst
- doc/changes/DM-38665.bugfix.md
- doc/changes/DM-38764.feature.md
- doc/changes/DM-38812.misc.rst
- doc/changes/DM-38900.feature.md
- doc/changes/DM-39402.misc.rst
- doc/changes/DM-39410.removal.md
- doc/changes/DM-39628.feature.rst
- doc/changes/DM-40032.feature.rst
- doc/changes/DM-40032.removal.rst
- doc/changes/DM-40367.feature.rst
- doc/changes/DM-40462.feature.md
- doc/lsst.utils/CHANGES.rst
> DM-40883 (main): v26 release notes

- .github/workflows/docstyle.yaml
- .pre-commit-config.yaml
- pyproject.toml
- python/lsst/utils/classes.py
- python/lsst/utils/db_auth.py
- python/lsst/utils/deprecated.py
- python/lsst/utils/inheritDoc.py
- python/lsst/utils/introspection.py
- python/lsst/utils/logging.py
- python/lsst/utils/packages.py
- python/lsst/utils/plotting/limits.py
- python/lsst/utils/tests.py
- python/lsst/utils/timer.py
- python/lsst/utils/wrappers.py
- tests/import_test/two/three/success.py
- tests/test_classes.py
- tests/test_decorators.py
- tests/test_deprecated.py
- tests/test_executables.py
- tests/test_getTempFilePath.py
- tests/test_introspection.py
- tests/test_packages.py
- tests/test_plotting_limits.py
> DM-42116: Add numpydoc validation

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .github/workflows/do_not_merge.yaml
- .github/workflows/docstyle.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- doc/changes/DM-40441.misc.md
- doc/conf.py
- pyproject.toml
- python/lsst/utils/logging.py
- python/lsst/utils/timer.py
- tests/test_db_auth.py
> DM-40441: annotate more timer functions as accepting LsstLogAdapter

- .pre-commit-config.yaml
- doc/changes/DM-22287.bugfix.rst
- doc/changes/DM-40441.misc.md
- doc/changes/DM-40803.misc.rst
- doc/changes/DM-40817.feature.md
- doc/changes/DM-42317.bugfix.rst
- doc/changes/DM-42391.misc.rst
- doc/lsst.utils/CHANGES.rst
- pyproject.toml
> DM-44569: v27 release notes (on branch)

- .github/workflows/build.yaml
- doc/changes/DM-44725.md
- pyproject.toml
- python/lsst/utils/plotting/__init__.py
- python/lsst/utils/plotting/figures.py
- python/lsst/utils/plotting/limits.py
- python/lsst/utils/tests.py
- requirements.txt
- tests/test_matplotlib_figures.py
> DM-44725: Add make_figure() utility to create non-interactive matplotlib Figures

- .pre-commit-config.yaml
- pyproject.toml
- python/lsst/utils/packages.py
- python/lsst/utils/tests.py
- requirements.txt
- tests/test_packages.py
> DM-45317: Investigate bad python version detection

- python/lsst/utils/tests.py
> DM-45483: Don't check files open in /sys/

- python/lsst/utils/introspection.py
- types.txt
> Fix formatting error in take_object_census.

- doc/changes/DM-46813.md
- python/lsst/utils/iteration.py
- tests/test_iteration.py
> DM-46813: Add sequence_to_range_str to compactify lists

- doc/changes/DM-44725.md
- doc/changes/DM-45007.feature.md
- doc/changes/DM-46813.md
- doc/lsst.utils/CHANGES.rst
> DM-47673: Add v28 release notes

- .pre-commit-config.yaml
- doc/changes/DM-44725.md
- doc/changes/DM-45007.feature.md
- doc/changes/DM-46813.md
- doc/lsst.utils/CHANGES.rst
> DM-47673: v28 release notes (cherry-picked)

- doc/changes/DM-47821.feature.rst
- python/lsst/utils/plotting/figures.py
- tests/test_matplotlib_figures.py
- [x ] ran Jenkins
- [ x] added a release note for user-visible changes to `doc/changes`
> DM-47821: Add utility functions for consistent multiband plot colors

- doc/changes/DM-34978.feature.rst
- python/lsst/utils/timer.py
- tests/decorator_test/disable_timer.py
- tests/test_timer.py
> DM-34978: Allow disabling the timing decorator

- python/lsst/utils/db_auth.py
- tests/test_db_auth.py
We cleaned up the API by removing the `None` option but other code relies on None correctly throwing a DbAuthNotFoundError.
> DM-49911: Revert to original API for DbAuth

- doc/changes/DM-50490.misc.rst
- python/lsst/utils/timer.py
- tests/test_timer.py
> DM-50490: Return duration in time_this context manager

- python/lsst/utils/timer.py
> DM-51276: Add support for Utc time format in duration_from_timeMethod

- doc/changes/DM-51690.misc.rst
- python/lsst/utils/plotting/figures.py
> DM-51690: Swap default plot color for i-band in utils scheme
